version: '3'
services:
  taiga-backup:
    build: .
    image: 52north/taiga-backup:latest
    environment:
      - TAIGA_USER=user
      - TAIGA_PASSWORD=pw
      - S3_KEY=s3key
      - S3_SECRET=s3secret
      - S3_REGION=eu-central-1
      - S3_BUCKET=target-bucket

    volumes:
      - ./data:/opt/taiga-backup/backups